exporters:
  debug:
    verbosity: detailed

extensions:
  zpages:

receivers:
  dummy:

service:
  extensions:
    - zpages
  pipelines:
    logs:
      exporters:
        - debug
      receivers:
        - dummy
